flowchart TD
  N0[Square]
  N1(Round)
  N2([Stadium])
  N3[[Subroutine]]
  N4[(Database)]
  N5((Circle))
  N6(((Double)))
  N7(-Ellipse-)
  N8{Diamond}
  N9{{Hexagon}}
  N10[/Lean right/]
  N11[\Lean left\]
  N12[/Trapezoid\]
  N13[\Inv trap/]
  N14>Odd shape]
